global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # API Service
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'

  # AI Service
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8001']
        labels:
          service: 'ai'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'database'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'cache'

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
        labels:
          service: 'storage'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
